buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.8.9'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}
plugins {
    id "org.sonarqube" version "6.2.0.5505"
}

sonar {
    properties {
        property "sonar.projectKey", "jonreboiro_ParkingJReboiro"
        property "sonar.organization", "jonreboiro"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.token", System.getenv('SONAR_TOKEN')
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}